### ISSUE TITLE
About the PyTorch version

### ISSUE THREAD

**Issue by flexibility2** [HongtaoYang/DAC-tensorflow#1]
Hi, I am very grateful for your source code! I try to implement this code with pytorch vision, but it does't work. I wonder if you have tried this? Can I communicate with you about this more specifically？ Thanks a lot!

**Comment by HongtaoYang** [comment]
Hi, thanks for your attention and support!

Personally I don't have much experience with PyTouch. Similar to your situation, my first few attempts of implementing this in tensorflow wasn't successful either. What I later found was you need to be careful with weights initialisation. I followed the authors initialisation configuration and then it worked. Your can check the authors original repo for details, or I believe such details are reflected in my code as well.

A example of this is:
```
conv4 = tf.layers.conv2d(conv3, 128, [3,3], [1,1], padding='valid', activation=None, \
                         kernel_initializer=tf.keras.initializers.he_normal())
conv4 = tf.layers.batch_normalization(conv4, axis=-1, epsilon=1e-5, training=True, trainable=False)
```

Hope that this is helpful. Don't hesitate to contact me if you have any further questions.

**Comment by flexibility2** [comment]
@HongtaoYang , Hi, thanks again, I finally solve the bug, it seems the reason is that I did't set the **"trainable=False"** in batch_normalization. However, I can't understand why to set this parameter to **False**, could you give me some explanation about this? Thanks a lot!
